name: test
on:
  - push
  - pull_request
  - workflow_call
permissions:
  contents: read

jobs:
  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@616f1f5863b4a3a73eb49cd0d16e8719bcd34e7a # next

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@616f1f5863b4a3a73eb49cd0d16e8719bcd34e7a # next

  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]
        db: [sqlite, postgres, mysql]
        redis-version: [10, 11]
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: session_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: session_test
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
      dynamodb-local:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Create DynamoDB Table
        env:
          AWS_ACCESS_KEY_ID: accessKeyId
          AWS_SECRET_ACCESS_KEY: secretAccessKey
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws dynamodb create-table --endpoint-url http://localhost:8000 \
            --table-name Session \
            --key-schema AttributeName=key,KeyType=HASH \
            --attribute-definitions AttributeName=key,AttributeType=S \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
          && aws dynamodb create-table --endpoint-url http://localhost:8000 \
            --table-name CustomKeySession \
            --key-schema AttributeName=sessionId,KeyType=HASH \
            --attribute-definitions AttributeName=sessionId,AttributeType=S \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Install @adonisjs/redis v${{ matrix.redis-version }}
        run: npm install --no-save @adonisjs/redis@${{ matrix.redis-version }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm test
        env:
          REDIS_HOST: 0.0.0.0
          REDIS_PORT: 6379
          DB_CONNECTION: ${{ matrix.db }}
          PG_HOST: 0.0.0.0
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: session_test
          MYSQL_HOST: 0.0.0.0
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: session_test

  test_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [latest]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm test
        env:
          NO_REDIS: true
          NO_DYNAMODB: true
          NO_DATABASE: true
